name: Build Electron App for Windows

on:
  push:
    branches:
      - main # ou a branch que você usar para deploy
  workflow_dispatch: # permite disparar manualmente

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # ou a versão compatível com sua aplicação

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run build && npx electron-builder --win

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/ # caminho padrão da pasta de output do electron-builder
